/*
 Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ce1.com/license
*/
(function(a){if("undefined"==typeof a)throw Error("jQuery should be loaded before CKEditor jQuery adapter.");if("undefined"==typeof ce1)throw Error("CKEditor should be loaded before CKEditor jQuery adapter.");ce1.config.jqueryOverrideVal="undefined"==typeof ce1.config.jqueryOverrideVal?!0:ce1.config.jqueryOverrideVal;a.extend(a.fn,{ce1Get:function(){var a=this.eq(0).data("ce1Instance");if(!a)throw"CKEditor is not initialized yet, use ce1() with a callback.";return a},
ce1:function(g,d){if(!ce1.env.isCompatible)throw Error("The environment is incompatible.");if(!a.isFunction(g))var k=d,d=g,g=k;var i=[],d=d||{};this.each(function(){var b=a(this),c=b.data("ce1Instance"),f=b.data("_ce1InstanceLock"),h=this,j=new a.Deferred;i.push(j.promise());if(c&&!f)g&&g.apply(c,[this]),j.resolve();else if(f)c.once("instanceReady",function(){setTimeout(function(){c.element?(c.element.$==h&&g&&g.apply(c,[h]),j.resolve()):setTimeout(arguments.callee,100)},0)},null,
null,9999);else{if(d.autoUpdateElement||"undefined"==typeof d.autoUpdateElement&&ce1.config.autoUpdateElement)d.autoUpdateElementJquery=!0;d.autoUpdateElement=!1;b.data("_ce1InstanceLock",!0);c=a(this).is("textarea")?ce1.replace(h,d):ce1.inline(h,d);b.data("ce1Instance",c);c.on("instanceReady",function(d){var e=d.editor;setTimeout(function(){if(e.element){d.removeListener();e.on("dataReady",function(){b.trigger("dataReady.ce1",[e])});e.on("setData",function(a){b.trigger("setData.ce1",
[e,a.data])});e.on("getData",function(a){b.trigger("getData.ce1",[e,a.data])},999);e.on("destroy",function(){b.trigger("destroy.ce1",[e])});e.on("save",function(){a(h.form).submit();return!1},null,null,20);if(e.config.autoUpdateElementJquery&&b.is("textarea")&&a(h.form).length){var c=function(){b.ce1(function(){e.updateElement()})};a(h.form).submit(c);a(h.form).bind("form-pre-serialize",c);b.bind("destroy.ce1",function(){a(h.form).unbind("submit",c);a(h.form).unbind("form-pre-serialize",
c)})}e.on("destroy",function(){b.removeData("ce1Instance")});b.removeData("_ce1InstanceLock");b.trigger("instanceReady.ce1",[e]);g&&g.apply(e,[h]);j.resolve()}else setTimeout(arguments.callee,100)},0)},null,null,9999)}});var f=new a.Deferred;this.promise=f.promise();a.when.apply(this,i).then(function(){f.resolve()});this.editor=this.eq(0).data("ce1Instance");return this}});ce1.config.jqueryOverrideVal&&(a.fn.val=ce1.tools.override(a.fn.val,function(g){return function(d){if(arguments.length){var k=
this,i=[],f=this.each(function(){var b=a(this),c=b.data("ce1Instance");if(b.is("textarea")&&c){var f=new a.Deferred;c.setData(d,function(){f.resolve()});i.push(f.promise());return!0}return g.call(b,d)});if(i.length){var b=new a.Deferred;a.when.apply(this,i).done(function(){b.resolveWith(k)});return b.promise()}return f}var f=a(this).eq(0),c=f.data("ce1Instance");return f.is("textarea")&&c?c.getData():g.call(f)}}))})(window.jQuery);